### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ZachCurtis** [OpenChassis/OpenChassis#1]
* OpenChassis Repo
   - [X] Document abstract goals of OpenChassis
   - [ ] Get the wiki up and running; documenting goals in detail
   - [ ] Provide basic use documentation on wiki, with LDoc support in the codebase

* OpenChassis General
   - [ ] Establish server and client single object endpoints supporting Roblox methodology patterns. Allow for event driven use in an exact or similar syntax to existing event methods.
   - [ ] Establish a human readable format to use in module scripts containing initialization settings

* OpenChassis Server
   - [ ] Decouple existing rigging module and modify to support mass and axle changes
   - [ ] Create server object particulars including;
      - [ ] Ownership reference
      - [ ] Current seated players
      - [ ] Properties and states for validation
      - [ ] Lightweight validation model

* OpenChassis Client
   - [ ] Create client object particulars including;
      - [ ] Top level properties and states for runtime use
      - [ ] Fully decoupled raw input layer/s 
      - [ ] Optional onboard contextual input handlers
         * Allow for disabling system and expose raw input setters
         - [ ] Mouse steering input schema
         - [ ] Gamepad input schema
         - [ ] Keyboard steering input schema (planned as a correction after perfection of above input methods)
      - [ ] Establish abstractions of all required systems;
         - [ ] Engine
             * Stick to naturally aspirated petrol at first, then introduce forced induction, then provide for diesel and electric variants
            - [ ] Given: throttle input, clutch input Use: rpm, power curve, Return: torque at flywheel
            - [ ] Model multiple power curves or modular algorithms allowing for proper representation of motor variations.
            - [ ] Approximate mechanical loss of engine internals
            - [ ] Model rolling resistance effects on engine retard given clutch stating
            - [ ] Simulate fuel usage and possibly octane variations. 

         - [ ] Transmission
             * Single clutch manual comes first as automatic and sequential are logic wrappers over it's functionality. CVT/Direct drive transmission calculations are unknown at the time of this writing.
            - [ ] Represent clutch as an input percent
            - [ ] Approximate clutch to flywheel interaction allowing for stalls and slip. 
            - [ ] Possibly provide helper to ease clutch when input goes from 0% to 100% under boolean input
            - [ ] Manage gear states and provide upshift and downshift setters
            - [ ] Implement gear ratios, final drive scaling, and transmission mechanical loss factor before passing torque to differential/s

         - [ ] Differentials
            - [ ] Allow for axle power splits to wheel0 and wheel1
            - [ ] Allow for drivetrain power splits to axle0 and axle1 for AWD/4x4
            - [ ] Open differential calculations
               * Torque routed to wheel under least resistance
               * Opposite spin under no power (non-essential fluff)
            - [ ] Limited slip differential calculations
               * Scale allowance of torque routing to wheel with most resistance (most traction)
            - [ ] Apply final mechanical loss factors before returning per wheel torque application

         - [ ] Aerodynamics
            - [ ] Raycast spam to generate 180 surface area calculations
            - [ ] Calculate wind resistance from surface area of current velocity vector.
            - [ ] Approximate downforce at both axles using direction and magnitude of velocity.

         - [ ] Force application to rig
             - [ ] Apply power torque as TorqueForce's in the wheel collider.
             - [ ] Apply brake forces as TorqueForce's in to the opposite roll direction of the wheels
             - [ ] Apply air resistance as a VectorForce to the main center brick.
             - [ ] Apply downforce as either VectorForce's in both axles, or VectorForce's in every suspension strut tower mount
             - [ ] Possibly apply engine gyro effect to some part using an undecided PGS body mover.
